version = 1
SPDX-PackageName = "gigya-native-screensets-engine"
SPDX-PackageSupplier = "Tal Mirmelshtein <tal.mirmelshtein@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/SAP/gigya-nSS"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 SAP SE or an SAP affiliate company and gigya-native-screensets-engine contributors"
SPDX-License-Identifier = "Apache-2.0"
